
# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# Website info
title: BEARly
description: A collection of Beginner friendly sayiings
cover: images/assets/cover.png
logo: images/assets/icon.png
logo_dark: images/assets/favicon.png
favicon: images/assets/favicon.ico
production_url: https://BEARly-Code.github.io
baseurl: /
source_url: https://github.com/BEARly-Code/BEARly-Code.github.io

# Styling
remote_theme : jekyller/jasper2

# Social info
navigation: False
subscribers: False
twitter: # TODO : Make
facebook: # TODO : Make

# Disqus
disqus: False

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml


# Permalinks
permalink: /:author/:title

# Excluded files
exclude:
  - README.md
  - .git*
  - CNAME
